version: '3.3'
services:
    influxdb:
        image: influxdb:latest
        container_name: influxdb

    telegraf:
        container_name: telegraf
        volumes:
            - '$PWD/telegraf.conf:/etc/telegraf/telegraf.conf:ro'
        ports:
            - '8173:8173'
        image: telegraf:latest
        links:
            - influxdb
